name: Export Dead Domains

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  export-domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install mysql-connector-python

      - name: Export Dead Domains
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          python hearse.py
          
      - name: Upload Exported Files
        uses: actions/upload-artifact@v3
        with:
          name: dead_domains_exports
          path: exports/
