name: Export Dead Domains

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  export-domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install mysql-connector-python
          pip install requests

      - name: Export Dead Domains
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          python src/hearse.py

      - name: Export
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add exports/*
          git commit -m "Add exported dead domains files: $(date --utc +'%Y-%m-%dT%H:%M:%SZ')"
          git push origin exported-domains
